CREATE TABLE Profesori
(
    ID INT PRIMARY KEY IDENTITY,
    Nume NVARCHAR(50) NOT NULL,
    Prenume NVARCHAR(50) NOT NULL,
    Catedra NVARCHAR(50) NOT NULL
)

CREATE TABLE Materii
(
    ID INT PRIMARY KEY IDENTITY,
    Denumire NVARCHAR(50) NOT NULL,
    AnStudiu INT NOT NULL
)

CREATE TABLE Sali
(
    ID INT PRIMARY KEY IDENTITY,
    NumarSala INT NOT NULL,
    Capacitate INT NOT NULL
)

CREATE TABLE OreProgramate
(
    ID INT PRIMARY KEY IDENTITY,
    ProfesorID INT NOT NULL FOREIGN KEY REFERENCES Profesori(ID),
    MaterieID INT NOT NULL FOREIGN KEY REFERENCES Materii(ID),
    SalaID INT NOT NULL FOREIGN KEY REFERENCES Sali(ID),
    Zi NVARCHAR(20) NOT NULL,
    OraInceput NVARCHAR(10) NOT NULL,
    OraSfarsit NVARCHAR(10) NOT NULL
)